// File generated by flutterfire configure tool.
// DO NOT EDIT by hand. Instead, run flutterfire configure to update.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    return android;
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDummyKeyForAndroid',
    appId: '1:123456789:android:abcdef1234567890',
    messagingSenderId: '123456789',
    projectId: 'bahaykusina',
    databaseURL: 'https://bahaykusina.firebaseio.com',
    storageBucket: 'bahaykusina.appspot.com',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDummyKeyForWeb',
    appId: '1:123456789:web:abcdef1234567890web',
    messagingSenderId: '123456789',
    projectId: 'bahaykusina',
    authDomain: 'bahaykusina.firebaseapp.com',
    databaseURL: 'https://bahaykusina.firebaseio.com',
    storageBucket: 'bahaykusina.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDummyKeyForIOS',
    appId: '1:123456789:ios:abcdef1234567890ios',
    messagingSenderId: '123456789',
    projectId: 'bahaykusina',
    databaseURL: 'https://bahaykusina.firebaseio.com',
    iosBundleId: 'com.example.bahaykusina',
    storageBucket: 'bahaykusina.appspot.com',
  );
}
